### ISSUE TITLE
Crash when tokens or titles are hidden.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/KillProof-Module#2]
**Ni at 12/22/2019 6:49:00 PM +00:00**
> Got a neat bug for you. The Killproof module crashes here (<https://github.com/TybaIt/Community-Module-Pack/blob/module-killproof/Kill%20Proof%20Module/KillProofModule.cs#L697>) if the user has tokens hidden, it'll probably crash in line 716 too if titles are hidden. KP's api currently returns `null` instead of an (empty) array for those fields.

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/658380490272669715

**Comment by dlamkins** [comment]
Ni suggested that it could look like the image below when one is hidden.

![image](https://user-images.githubusercontent.com/1950594/72261049-176b2400-35e2-11ea-81b0-49dae6410dbb.png)

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/666154099888357387

**Comment by dlamkins** [comment]
Resolved in 4094b9458a38eedf5518c339283618fee656433d.  Split button idea into #3 enhancement.
