### ISSUE TITLE
Incorrect Unstable Fractal Essence Display

### ISSUE THREAD

**Issue by Arthua** [blish-hud/KillProof-Module#27]
Like the title says a friend of mine as a drasticly different display of "Unstable Fractal Essence" in the website (kp.me) and in the Blish hud.
From our math the number displayed on the website is the correct one.

![Blish hud image](https://user-images.githubusercontent.com/15057374/99030574-4c7f3480-256d-11eb-91e3-ad21ebd73b85.png)
![KP me image](https://user-images.githubusercontent.com/15057374/99030622-6ae53000-256d-11eb-96ff-2c2a5c0ae1a3.png)

**Comment by agaertner** [comment]
The is not related to the module but rather how killproof.me builds its API. You are better off messaging Leaky, the author of killproof.me.
