### ISSUE TITLE
Indicate when tokens, titles, or LI details have been hidden.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/KillProof-Module#3]
A continuation of #2.  Right now if tokens, titles, or LI details have been hidden by the user, we silently ignore them in the UI and make an info log entry.

In the future, we should indicate in the UI somehow that it has been explicitly hidden and is not just missing.

Example made by Ni:
![image](https://user-images.githubusercontent.com/1950594/72261049-176b2400-35e2-11ea-81b0-49dae6410dbb.png)

**Comment by agaertner** [comment]
What greater value is there for the viewer instead of silently ignoring those entries?

**Comment by dlamkins** [comment]
It was a suggestion from somebody else who felt there was value.

**Comment by agaertner** [comment]
I don't think there is any value in cluttering the panels with empty token spaces. May decrease the user experience when sorting for the same reason why token amounts of 0 aren't shown.
I want to encourage not hiding tokens because I see absolutely no point in it.

Closing for now.
